//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessMasterApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreStocks
    {
        public int StoreStockID { get; set; }
        public int StoreID { get; set; }
        public int BookID { get; set; }
        public Nullable<int> Stock { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Stores Stores { get; set; }
    }
}
